"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the mobile bridge plugin"
permissions = [
  "allow-check-permissions",
  "allow-request-permissions",
  "allow-register-listener",
  "allow-remove-listener",
  "allow-scan-network",
  "allow-cancel-scan",
  "allow-share",
  "allow-select-ui",
  "allow-get-selected-ui",
  "allow-get-default-server-url",
  "allow-set-default-server-url",
  "allow-get-chamber-server-url",
  "allow-set-chamber-server-url",
  "allow-probe-chamber-server-url",
]
